### PR TITLE
add option to hide ticks and circle

### LINKED ISSUE #11: Ambient/night mode incorrectly drawn when tick marks and circles set to same color
I love this watch face and use it daily, however I "hide" the outside circle and tick-marks by setting them all to the same color. In normal mode this works great and looks like this:
img_20180816_195708

However in ambient mode, a white circle outline is shown and is slightly lopsided and goes off screen. Ideally I'd like to hide it i ambient mode as well, but this looks like a bug and not a feature.
img_20180816_195642

### PR DESCRIPTION
**Pull request by lanrat**
Fixes #11

### CODE REVIEW

**Comment by Nxt3** [comment]
Why is so much code being reformated?

**Comment by lanrat** [comment]
In `drawBackground()` the circle logic was moved inside an if condition checking the value of `mHideCircle`. This indented a chunk of code.

**Comment by Nxt3** [comment]
Oops I missed that. Lemme review this tomorrow and I'll see about merging it. Thanks for the work!

**Comment by Nxt3** [comment]
Great work on this! It's much appreciated :)

I'll push an update for this later today or tomorrow.

**Comment by lanrat** [comment]
I'm thinking of making some more changes to this watch face to make it more like [minimalin](https://github.com/GringerApps/minimalin) for the pebble. Since that may take the watch face in a different direction than the original goal of this one (to mimic the demo at IO) I'm happy to maintain my own fork. Or I can backport all the changes here as a pull request. @Nxt3 do you have a preference?

**Comment by Nxt3** [comment]
I actually had another watchface in mind. I wanted to create one that looks like https://play.google.com/store/apps/details?id=eu.ttmm.wear.modeldigittmm

But allow more customization. I started work months ago but haven't picked it up. Wanted to do it in Kotlin, too. 

I personally think if your goal is to make that minimalin look-a-like, it should be it's own watchface independent of IO Classic. You're more than happy to for this and rework everything. I'd love a watchface like that.

**Pull request merged**
